# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bloomfilter}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew L. Johnson"]
  s.date = %q{2010-10-09}
  s.description = %q{}
  s.email = %q{ryan@agileproductions.com}
  s.files = [
    ".config",
     "ReadMe",
     "VERSION",
     "bitset/bitset-1.0/Makefile",
     "bitset/bitset-1.0/bitset.bundle",
     "bitset/bitset-1.0/bitset.c",
     "bitset/bitset-1.0/extconf.rb",
     "bitset/bitset-1.0/sample/htmlentity.rb",
     "bitset/bitset-1.0/sample/xmlchar.rb",
     "bitset/bitset-1.0/test.rb",
     "lib/bloomfilter.rb",
     "lib/bloomfilter/simplevector.rb",
     "setup.rb",
     "test/tc_basic.rb",
     "test/testsuite.rb"
  ]
  s.homepage = %q{http://github.com/ryanstout/bloomfilter/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Bloomfilter implementation}
  s.test_files = [
    "test/tc_basic.rb",
     "test/testsuite.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

